DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS people;

CREATE TABLE IF NOT EXISTS people
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    year INT          NOT NULL CHECK ( year > 1926 )
);

CREATE TABLE IF NOT EXISTS books
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    year   INT          NOT NULL,
    person_id INT REFERENCES people(id) ON DELETE SET NULL
);

INSERT INTO people(name, year)
VALUES ('Зиннурова Зинаида Федоровна', 1981),
       ('Алексеев Алексей Владимирович', 2000),
       ('Сунгатова Рената Александровна', 1985);

INSERT INTO books(title, author, year, person_id)
VALUES ('Над пропастью во ржи', 'Джером Селенджер', 1951, 1),
       ('День опричника', 'Владимир Сорокин',  2006, 1),
       ('Философия Java', 'Брюс Эккель',  2018, 3);
